# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

provider:
  name: aws
  architecture: x86_64

service: 'test-bot'

functions:

  chat:
    handler: routes.api
    events:
      - httpApi:
          path: /api
          method: post
      - httpApi:
          path: /webhook/{channel}
          method: post
      - httpApi:
          path: /webhook/{channel}
          method: get
      - httpApi:
          path: /webhook/{channel}/{id}
          method: post
      - httpApi:
          path: /webhook/{channel}/{id}
          method: get

  wsConnected:
    handler: routes.connect
    events:
      - websocket:
          route: $connect

  wsDisconnected:
    handler: routes.disconnect
    memorySize: 192
    events:
      - websocket:
          route: $disconnect

  defaultMessage:
    handler: routes.default
    events:
      - websocket:
          route: $default

