name: Push

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js ${{ matrix.node-version }} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Npm install
        run: npm install && cd documentation && npm install --legacy-peer-deps && cd ..

      - name: Test
        run: npm run Test

  build-docs:
    name: build docs
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Rewrite gatsby confing inside smoothdoc
        run: cp documentation/smooth-doc-gatsby-config.js documentation/node_modules/smooth-doc/gatsby-config.js

      - name: Generate mdx documentation files
        run: node bin/makeApiDoc

      - name: Build documentation website with gatsby
        run: cd documentation && npm run build

      - name: Deploy documentation to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/public # The folder the action should deploy.
