name: Push

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js ${{ matrix.node-version }} setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: https://npm.pkg.github.com
          scope: '@wingbotai'

      - name: Npm install
        run: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WINGBOT_PCKG_READ_PAT }}

      - name: Test
        run: npm run test

  build-docs:
    name: build docs
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Npm install
        run: cd documentation && npm install --legacy-peer-deps && cd ..

      - name: Rewrite gatsby confing inside smoothdoc
        run: cp documentation/smooth-doc-gatsby-config.js documentation/node_modules/smooth-doc/gatsby-config.js

      - name: Generate mdx documentation files
        run: node bin/makeApiDoc

      - name: Build documentation website with gatsby
        run: cd documentation && npm run build

  deploy-docs:
    name: deploy docs
    needs: build-docs
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy documentation to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/public # The folder the action should deploy.
